In [2]:
from kpi_local import create_report
from kpi_local import create_report_fullyear
from kpi_local import query_employee
import pandas as pd
import plotly.express as px
import numpy as np


pd.set_option('display.max_columns', 500)

2023-02-21 10:44:37.086
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\minhp\Anaconda3\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]

In [4]:
month = 1
sale = 1000000
df_employee_month_sale = create_report(file_path_report='Evaluation Report.csv',file_path_loan_status='Loan Status.csv',month=1,sale=1000000)

KeyError: "['Attendance', 'Collaboration', 'Work Behavior'] not in index"

In [8]:
evaluation_file = 'https://cloud.pacificwide.com/dd/10zNRyog88/Evaluation_Report.csv_'
loan_status = 'https://cloud.pacificwide.com/dd/2t4HA95NDp/Loan_Status.csv_'
kpi_summary = 'https://cloud.pacificwide.com/dd/jRIpFXZrDz/KPI_Summary.csv_'

df_fullyear = create_report_fullyear(evaluation_file,loan_status,kpi_summary)
df_fullyear.head()

,Month,Name,Title,Number of Loan Completed,Number of Loan Takeover,Number of Loan Completed Within 3 Weeks,Number of Difficult Loan,Number of Missed Milestone,Number of Loan Denied,Number of Loan Withdrawn,Check-list Forms & Procedure (%),Attendance,Teamwork,Collaboration,Work Behavior,Learning,Responsibility,Customer: Good Feedback,Customer: Bad Feedback,Number of Normal Loan Completed,All Loan Completed,KPI,Work Score,Attitude Score,Total Loan Assigned,Withdrawn Rate (%),Denial Rate (%),Work Completion Score,Final Score,Work Score (%),Work Completion Score (%),Attitude Score (%),Final Score (%),Alert,Month Text
0,1,LONG,Full-time Junior Loan Processor,3,0.2,0,1,1,1,1,1.0,9,9,10,10,9,8,0,0,2,3.645946,15.0,2.430631,9.166667,5,20.0,20.0,7.291892,5.854234,24.0,73.0,92.0,59.0,CHECK,January
1,1,DAT,Part-time Junior Loan Processor,2,1.2,0,0,2,0,0,0.8,9,7,10,10,8,8,0,0,2,2.403750,5.0,4.807500,8.666667,2,0.0,0.0,12.018750,7.312667,48.0,120.0,87.0,73.0,NORMAL,January
2,1,HUY,Part-time Senior Loan Processor,4,1.0,0,0,5,1,1,0.7,9,7,10,10,8,8,0,0,4,3.214286,10.0,3.214286,8.666667,6,17.0,17.0,5.357143,5.502381,32.0,54.0,87.0,55.0,CHECK,January
3,1,VU,Full-time Junior Loan Processor,5,0.4,1,1,6,1,1,0.5,7,8,7,7,8,8,0,0,3,2.825000,15.0,1.883333,7.500000,7,14.0,14.0,4.035714,4.372143,19.0,40.0,75.0,44.0,WARNING!,January
4,1,THAI,Full-time Senior Loan Processor,2,0.6,1,1,8,2,2,0.9,6,6,6,8,5,6,1,0,0,2.746173,20.0,1.373086,6.166667,6,33.0,33.0,4.576955,4.793984,14.0,46.0,62.0,48.0,WARNING!,January

In [34]:
df = df_fullyear[df_fullyear['Name'].isin(['DAT','MINH'])]
df

,Month,Name,Title,Number of Loan Completed,Number of Loan Takeover,Number of Loan Completed Within 3 Weeks,Number of Difficult Loan,Number of Missed Milestone,Number of Loan Denied,Number of Loan Withdrawn,Check-list Forms & Procedure (%),Attendance,Teamwork,Collaboration,Work Behavior,Learning,Responsibility,Customer: Good Feedback,Customer: Bad Feedback,Number of Normal Loan Completed,All Loan Completed,KPI,Work Score,Attitude Score,Total Loan Assigned,Withdrawn Rate (%),Denial Rate (%),Work Completion Score,Final Score,Work Score (%),Work Completion Score (%),Attitude Score (%),Final Score (%),Alert,Month Text
1,1,DAT,Part-time Junior Loan Processor,2,1.2,0,0,2,0,0,0.8,9,7,10,10,8,8,0,0,2,2.403750,5.0,4.807500,8.666667,2,0.0,0.0,12.018750,7.312667,48.0,120.0,87.0,73.0,NORMAL,January
0,2,DAT,Part-time Junior Loan Processor,4,0.2,0,2,0,1,1,1.0,8,5,8,6,4,5,0,1,2,5.200000,5.0,10.400000,6.000000,6,17.0,17.0,8.666667,6.253333,104.0,87.0,60.0,63.0,CHECK,February
0,3,DAT,Part-time Junior Loan Processor,5,0.2,0,0,2,1,2,0.3,9,5,8,6,5,6,0,0,5,1.303590,5.0,2.607179,6.500000,8,25.0,12.0,1.629487,3.708051,26.0,16.0,65.0,37.0,WARNING!,March
0,4,DAT,Full-time Junior Loan Processor,6,1.0,2,1,9,1,1,1.0,9,9,10,10,9,8,0,0,3,8.288235,15.0,5.525490,9.166667,8,12.0,12.0,10.360294,7.396373,55.0,104.0,92.0,74.0,NORMAL,April
0,5,DAT,Full-time Senior Loan Processor,6,0.2,0,1,7,1,1,0.7,6,6,6,8,5,6,0,0,5,4.391493,19.0,2.311312,6.166667,8,12.0,12.0,5.489366,4.257933,23.0,55.0,62.0,43.0,WARNING!,May
0,6,DAT,Full-time Senior Loan Processor,7,0.2,0,3,5,1,2,1.0,7,8,8,5,8,9,0,1,4,8.585057,19.0,4.518451,7.500000,10,20.0,10.0,8.585057,5.072547,45.0,86.0,75.0,51.0,CHECK,June
0,7,DAT,Full-time Senior Loan Processor,1,0.2,0,4,7,1,1,1.0,8,4,9,6,4,5,0,0,-3,2.762500,19.0,1.453947,6.000000,3,33.0,33.0,9.208333,4.677851,15.0,92.0,60.0,47.0,WARNING!,July
0,8,DAT,Full-time Junior Loan Processor,5,0.0,0,5,5,1,1,0.7,7,8,7,7,8,8,0,0,0,5.059524,14.0,3.613946,7.500000,7,14.0,14.0,7.227891,5.529762,36.0,72.0,75.0,55.0,CHECK,August
3,9,DAT,Part-time Senior Loan Processor,7,0.4,0,1,5,2,2,1.0,7,4,5,5,8,8,0,0,6,7.773418,10.0,7.773418,6.166667,11,18.0,18.0,7.066743,6.212041,78.0,71.0,62.0,62.0,CHECK,September
2,12,MINH,Full-time Senior Loan Processor,7,0.2,0,1,10,1,1,1.0,7,8,5,9,8,9,0,0,6,7.440260,19.0,3.915926,7.666667,9,11.0,11.0,8.266955,5.894836,39.0,83.0,77.0,59.0,CHECK,December
3,12,DAT,Part-time Junior Loan Processor,3,1.0,0,1,10,1,2,0.9,9,5,8,6,5,6,0,0,2,3.556173,5.0,7.112346,6.500000,6,33.0,17.0,5.926955,5.919095,71.0,59.0,65.0,59.0,CHECK,December

In [30]:
fig = px.line(data_frame=df_fullyear,x='Month',y='Final Score (%)',color ='Name')
fig

In [7]:
df_fullyear['Name'].unique()

NameError: name 'df_fullyear' is not defined

In [ ]:
df_fullyear_month = df_fullyear.groupby('Month Text').mean().reset_index()
df_fullyear_month

,Month Text,Month,Number of Loan Completed,Number of Loan Takeover,Number of Loan Completed Within 3 Weeks,Number of Difficult Loan,Number of Missed Milestone,Number of Loan Denied,Number of Loan Withdrawn,Check-list Forms & Procedure (%),Attendee,Teamwork,Colab,Work behavior,Learning,Responsibility,Customer: Good Feedback,Customer: Bad Feedback,Number of Normal Loan Completed,All Loan Completed,KPI,Work Score,Attitude Score,Total Loan Assigned,Withdrawn Rate (%),Denial Rate (%),Work Completion Score,Final Score,Work Score (%),Work Completion Score (%),Attitude Score (%),Final Score (%)
0,April,4.0,4.00,0.40,0.75,1.75,5.00,0.75,0.75,0.975,8.50,7.75,9.25,9.25,8.25,8.00,0.50,0.00,1.50,5.375681,10.75,4.992886,8.500000,5.50,10.75,10.75,13.332962,8.064458,50.00,133.50,85.25,80.75
1,August,8.0,5.00,0.25,0.25,4.00,5.25,1.25,1.50,0.700,6.50,6.75,6.50,7.50,6.25,5.75,0.00,0.00,0.75,4.957372,10.75,5.765408,6.541667,7.75,18.75,16.50,6.401801,5.626649,57.75,64.00,65.50,56.25
2,December,12.0,4.50,0.45,0.25,0.75,5.75,1.25,1.75,0.825,6.25,6.50,6.50,7.50,6.50,6.75,0.00,0.00,3.50,4.612009,10.00,5.045205,6.666667,7.50,26.00,17.00,5.669712,5.314171,50.50,56.75,66.75,53.25
3,February,2.0,2.75,0.30,0.00,1.25,3.50,1.25,1.75,0.775,6.00,6.50,6.50,7.50,6.25,6.50,0.00,0.50,1.50,2.622817,12.50,3.579960,6.541667,5.75,30.00,21.50,4.632710,4.117197,35.75,46.50,65.50,41.25
4,January,1.0,3.20,0.68,0.40,0.60,4.40,1.00,1.00,0.780,8.00,7.40,8.60,9.00,7.60,7.60,0.20,0.00,2.20,2.967031,13.00,2.741767,8.033333,5.20,16.80,16.80,6.656091,5.567082,27.40,66.60,80.60,55.80
5,July,7.0,2.75,0.10,0.25,4.25,5.00,0.75,0.75,0.875,8.75,6.75,9.75,9.00,7.25,7.25,0.00,0.25,-1.75,4.018736,11.00,4.828293,8.125000,4.25,16.00,16.00,14.814278,7.411343,48.25,148.00,81.50,74.25
6,June,6.0,5.25,0.15,0.25,1.75,4.25,1.75,1.25,1.000,8.00,6.25,7.25,6.25,6.50,7.25,0.00,0.25,3.25,6.231842,11.50,7.221815,6.916667,8.25,15.25,24.00,7.315508,6.146313,72.25,73.25,69.25,61.25
7,March,3.0,3.50,0.75,0.50,0.75,3.75,1.25,2.50,0.825,8.25,5.25,7.50,6.50,5.50,6.25,0.25,0.25,2.25,3.755125,12.50,3.005005,6.541667,7.25,32.50,18.00,5.764837,4.671136,30.25,57.50,65.50,46.75
8,May,5.0,5.25,0.40,0.00,1.00,2.50,1.50,1.25,0.850,5.75,6.00,6.75,7.25,5.50,5.75,0.25,0.00,4.25,5.119508,11.75,5.352000,6.166667,8.00,15.00,18.75,6.472406,5.616748,53.50,64.75,61.75,56.50
9,November,11.0,4.50,0.05,1.00,0.00,2.50,1.25,1.25,0.875,7.50,6.50,7.75,7.75,6.25,6.75,0.00,0.00,3.50,4.256875,10.00,4.715755,7.083333,7.00,18.25,19.50,6.098661,5.467792,47.25,61.00,71.00,54.50
10,October,10.0,3.25,0.00,0.25,0.75,3.50,1.00,1.75,0.925,8.75,7.00,9.25,8.75,6.50,6.75,0.00,0.00,2.25,2.972565,11.00,3.086512,7.833333,6.00,22.00,12.75,7.157236,5.490734,31.00,71.50,78.50,54.75
11,September,9.0,5.25,1.00,0.00,1.25,3.50,1.50,2.00,0.900,6.75,5.50,6.50,6.50,6.50,7.75,0.25,0.00,4.00,6.295845,10.50,6.415415,6.583333,8.75,25.00,16.75,7.042501,6.216458,64.25,70.50,66.00,62.25

In [ ]:
cols_to_show = ['Month Text','Work Completion Score','Final Score', 'Work Score (%)', 'Work Completion Score (%)',
                 'Attitude Score (%)', 'Final Score (%)','Month']

df_fullyear_month = df_fullyear_month[cols_to_show]
df_fullyear_month = df_fullyear_month.sort_values(by='Month').reset_index().drop(columns='index')
df_fullyear_month

,Month Text,Work Completion Score,Final Score,Work Score (%),Work Completion Score (%),Attitude Score (%),Final Score (%),Month
0,January,6.656091,5.567082,27.40,66.60,80.60,55.80,1.0
1,February,4.632710,4.117197,35.75,46.50,65.50,41.25,2.0
2,March,5.764837,4.671136,30.25,57.50,65.50,46.75,3.0
3,April,13.332962,8.064458,50.00,133.50,85.25,80.75,4.0
4,May,6.472406,5.616748,53.50,64.75,61.75,56.50,5.0
5,June,7.315508,6.146313,72.25,73.25,69.25,61.25,6.0
6,July,14.814278,7.411343,48.25,148.00,81.50,74.25,7.0
7,August,6.401801,5.626649,57.75,64.00,65.50,56.25,8.0
8,September,7.042501,6.216458,64.25,70.50,66.00,62.25,9.0
9,October,7.157236,5.490734,31.00,71.50,78.50,54.75,10.0
10,November,6.098661,5.467792,47.25,61.00,71.00,54.50,11.0
11,December,5.669712,5.314171,50.50,56.75,66.75,53.25,12.0

In [ ]:
df_loan_status = pd.read_csv('Loan Status.csv')
df_loan_status_train = df_loan_status[['Month','Loan Amount']].iloc[0:12]
df_loan_status_test = df_loan_status[['Month','Loan Amount']].iloc[12:17]
df_loan_status_test

       Month  Loan Amount
12   January      1950000
13  February      4191960
14     March     11046500
15     April      3133000
16       May      6668430

In [ ]:
df_fullyear_sale_goal_train = pd.merge(df_fullyear_month,df_loan_status_train,left_on='Month Text',right_on='Month',how='inner')
df_fullyear_sale_goal_test = pd.merge(df_fullyear_month,df_loan_status_test,left_on='Month Text',right_on='Month',how='inner')
df_fullyear_sale_goal_train

,Month Text,Work Completion Score,Final Score,Work Score (%),Work Completion Score (%),Attitude Score (%),Final Score (%),Month_x,Month_y,Loan Amount
0,January,6.656091,5.567082,27.40,66.60,80.60,55.80,1.0,January,8891000
1,February,4.632710,4.117197,35.75,46.50,65.50,41.25,2.0,February,13038000
2,March,5.764837,4.671136,30.25,57.50,65.50,46.75,3.0,March,21026000
3,April,13.332962,8.064458,50.00,133.50,85.25,80.75,4.0,April,9059000
4,May,6.472406,5.616748,53.50,64.75,61.75,56.50,5.0,May,12877000
5,June,7.315508,6.146313,72.25,73.25,69.25,61.25,6.0,June,12487646
6,July,14.814278,7.411343,48.25,148.00,81.50,74.25,7.0,July,7960653
7,August,6.401801,5.626649,57.75,64.00,65.50,56.25,8.0,August,16840000
8,September,7.042501,6.216458,64.25,70.50,66.00,62.25,9.0,September,9996000
9,October,7.157236,5.490734,31.00,71.50,78.50,54.75,10.0,October,14282870
10,November,6.098661,5.467792,47.25,61.00,71.00,54.50,11.0,November,8613096
11,December,5.669712,5.314171,50.50,56.75,66.75,53.25,12.0,December,10632346

In [ ]:
df_fullyear_sale_goal_test

,Month Text,Work Completion Score,Final Score,Work Score (%),Work Completion Score (%),Attitude Score (%),Final Score (%),Month_x,Month_y,Loan Amount
0,January,6.656091,5.567082,27.40,66.60,80.60,55.80,1.0,January,1950000
1,February,4.632710,4.117197,35.75,46.50,65.50,41.25,2.0,February,4191960
2,March,5.764837,4.671136,30.25,57.50,65.50,46.75,3.0,March,11046500
3,April,13.332962,8.064458,50.00,133.50,85.25,80.75,4.0,April,3133000
4,May,6.472406,5.616748,53.50,64.75,61.75,56.50,5.0,May,6668430

In [ ]:
X_train = df_fullyear_sale_goal_train.drop(columns=['Month_x','Month_y','Loan Amount'])
y_train = df_fullyear_sale_goal_train['Loan Amount']
X_test = df_fullyear_sale_goal_test.drop(columns=['Month_x','Month_y','Loan Amount'])
y_test = df_fullyear_sale_goal_test['Loan Amount']

In [ ]:
from lazypredict.Supervised import LazyRegressor
reg = LazyRegressor(verbose=1, ignore_warnings=False,predictions=True)
models, predictions = reg.fit(X_train,X_test, y_train, y_test)

 14%|█▍        | 6/42 [00:00<00:00, 54.03it/s]

{'Model': 'AdaBoostRegressor', 'R-Squared': -4.821065056879706, 'Adjusted R-Squared': 8.761420075839608, 'RMSE': 7780162.865812052, 'Time taken': 0.04833412170410156}
{'Model': 'BaggingRegressor', 'R-Squared': -7.893470654396909, 'Adjusted R-Squared': 12.857960872529212, 'RMSE': 9616634.277224537, 'Time taken': 0.01766180992126465}
{'Model': 'BayesianRidge', 'R-Squared': -4.3737993721973325, 'Adjusted R-Squared': 8.165065829596443, 'RMSE': 7475292.417216803, 'Time taken': 0.015692710876464844}
{'Model': 'DecisionTreeRegressor', 'R-Squared': -4.763931820348119, 'Adjusted R-Squared': 8.685242427130824, 'RMSE': 7741887.914152465, 'Time taken': 0.008019208908081055}
{'Model': 'DummyRegressor', 'R-Squared': -4.373799372199783, 'Adjusted R-Squared': 8.16506582959971, 'RMSE': 7475292.417218507, 'Time taken': 0.007707118988037109}
{'Model': 'ElasticNet', 'R-Squared': -4.812700818273851, 'Adjusted R-Squared': 8.750267757698467, 'RMSE': 7774571.231699278, 'Time taken': 0.012831926345825195}
{'Model': 'ElasticNetCV', 'R-Squared': -4.372441099290452, 'Adjusted R-Squared': 8.163254799053934, 'RMSE': 7474347.636054174, 'Time taken': 0.044730186462402344}
{'Model': 'ExtraTreeRegressor', 'R-Squared': -4.763931820348119, 'Adjusted R-Squared': 8.685242427130824, 'RMSE': 7741887.914152465, 'Time taken': 0.01200103759765625}
{'Model': 'ExtraTreesRegressor', 'R-Squared': -4.763931820348119, 'Adjusted R-Squared': 8.685242427130824, 'RMSE': 7741887.914152465, 'Time taken': 0.06157565116882324}
{'Model': 'GammaRegressor', 'R-Squared': -4.664484849500916, 'Adjusted R-Squared': 8.552646466001221, 'RMSE': 7674810.6870881785, 'Time taken': 0.01483297348022461}
{'Model': 'GaussianProcessRegressor', 'R-Squared': -4.763931818431868, 'Adjusted R-Squared': 8.685242424575824, 'RMSE': 7741887.912865548, 'Time taken': 0.018450498580932617}

 43%|████▎     | 18/42 [00:00<00:00, 45.23it/s]

{'Model': 'GradientBoostingRegressor', 'R-Squared': -4.763822643965196, 'Adjusted R-Squared': 8.68509685862026, 'RMSE': 7741814.593080296, 'Time taken': 0.020565032958984375}
{'Model': 'HistGradientBoostingRegressor', 'R-Squared': -4.373799372199783, 'Adjusted R-Squared': 8.16506582959971, 'RMSE': 7475292.417218507, 'Time taken': 0.03540349006652832}
{'Model': 'HuberRegressor', 'R-Squared': -3.409539378727449, 'Adjusted R-Squared': 6.879385838303265, 'RMSE': 6771487.397587812, 'Time taken': 0.016230106353759766}
{'Model': 'KNeighborsRegressor', 'R-Squared': -5.27296062713921, 'Adjusted R-Squared': 9.36394750285228, 'RMSE': 8076510.140403862, 'Time taken': 0.012668848037719727}
{'Model': 'KernelRidge', 'R-Squared': -0.9398763940975798, 'Adjusted R-Squared': 3.586501858796773, 'RMSE': 4491325.087741366, 'Time taken': 0.013610124588012695}
{'Model': 'Lars', 'R-Squared': -51.6630596147278, 'Adjusted R-Squared': 71.21741281963706, 'RMSE': 23401328.08425497, 'Time taken': 0.013707399368286133}
{'Model': 'LarsCV', 'R-Squared': -4.267015847091901, 'Adjusted R-Squared': 8.022687796122534, 'RMSE': 7400648.446464748, 'Time taken': 0.021612167358398438}
{'Model': 'Lasso', 'R-Squared': -5.262084010042429, 'Adjusted R-Squared': 9.349445346723238, 'RMSE': 8069505.216814952, 'Time taken': 0.014654397964477539}
{'Model': 'LassoCV', 'R-Squared': -4.267098510383211, 'Adjusted R-Squared': 8.02279801384428, 'RMSE': 7400706.521053459, 'Time taken': 0.06376528739929199}
{'Model': 'LassoLars', 'R-Squared': -3.82229445737872, 'Adjusted R-Squared': 7.4297259431716265, 'RMSE': 7081321.701580657, 'Time taken': 0.013364553451538086}

 69%|██████▉   | 29/42 [00:00<00:00, 47.28it/s]

{'Model': 'LassoLarsCV', 'R-Squared': -4.267015847091901, 'Adjusted R-Squared': 8.022687796122534, 'RMSE': 7400648.446464748, 'Time taken': 0.02235269546508789}
{'Model': 'LassoLarsIC', 'R-Squared': -4.304493062249289, 'Adjusted R-Squared': 8.072657416332385, 'RMSE': 7426931.266918017, 'Time taken': 0.01170802116394043}
{'Model': 'LinearRegression', 'R-Squared': -3.8203485678614566, 'Adjusted R-Squared': 7.4271314238152755, 'RMSE': 7079892.831968822, 'Time taken': 0.011038780212402344}
{'Model': 'LinearSVR', 'R-Squared': -2.8017277277235113, 'Adjusted R-Squared': 6.068970303631348, 'RMSE': 6287499.550562147, 'Time taken': 0.010735273361206055}
{'Model': 'MLPRegressor', 'R-Squared': -2.8020817893378394, 'Adjusted R-Squared': 6.069442385783786, 'RMSE': 6287792.326711729, 'Time taken': 0.05230116844177246}
{'Model': 'NuSVR', 'R-Squared': -3.3700027775061763, 'Adjusted R-Squared': 6.826670370008235, 'RMSE': 6741061.950900989, 'Time taken': 0.00867605209350586}
{'Model': 'OrthogonalMatchingPursuit', 'R-Squared': -4.885205963136338, 'Adjusted R-Squared': 8.846941284181783, 'RMSE': 7822909.300560345, 'Time taken': 0.010271549224853516}
{'Model': 'OrthogonalMatchingPursuitCV', 'R-Squared': -4.885205963136338, 'Adjusted R-Squared': 8.846941284181783, 'RMSE': 7822909.300560345, 'Time taken': 0.012660503387451172}
{'Model': 'PassiveAggressiveRegressor', 'R-Squared': -2.4184277124989806, 'Adjusted R-Squared': 5.557903616665307, 'RMSE': 5962119.3036788525, 'Time taken': 0.010623693466186523}
{'Model': 'PoissonRegressor', 'R-Squared': -4.057167260231826, 'Adjusted R-Squared': 7.742889680309101, 'RMSE': 7251721.564996253, 'Time taken': 0.021853208541870117}
{'Model': 'QuantileRegressor', 'R-Squared': -3.5614324255718834, 'Adjusted R-Squared': 7.081909900762511, 'RMSE': 6887126.889955225, 'Time taken': 0.017405271530151367}
{'Model': 'RANSACRegressor', 'R-Squared': -4.248296923979757, 'Adjusted R-Squared': 7.9977292319730084, 'RMSE': 7387485.824784867, 'Time taken': 0.018589496612548828}

100%|██████████| 42/42 [00:00<00:00, 45.10it/s]

{'Model': 'RandomForestRegressor', 'R-Squared': -6.2510282813188605, 'Adjusted R-Squared': 10.668037708425146, 'RMSE': 8683349.097715449, 'Time taken': 0.07935214042663574}
{'Model': 'Ridge', 'R-Squared': -5.065716105326172, 'Adjusted R-Squared': 9.087621473768229, 'RMSE': 7941974.748769945, 'Time taken': 0.008506536483764648}
{'Model': 'RidgeCV', 'R-Squared': -4.728296343396199, 'Adjusted R-Squared': 8.637728457861598, 'RMSE': 7717918.719518374, 'Time taken': 0.009191036224365234}
{'Model': 'SGDRegressor', 'R-Squared': -2.861067985921823, 'Adjusted R-Squared': 6.1480906478957635, 'RMSE': 6336379.587728499, 'Time taken': 0.012293338775634766}
{'Model': 'SVR', 'R-Squared': -3.651496910369838, 'Adjusted R-Squared': 7.201995880493117, 'RMSE': 6954786.945701258, 'Time taken': 0.009009361267089844}
{'Model': 'TransformedTargetRegressor', 'R-Squared': -3.8203485678614566, 'Adjusted R-Squared': 7.4271314238152755, 'RMSE': 7079892.831968822, 'Time taken': 0.009922266006469727}
{'Model': 'TweedieRegressor', 'R-Squared': -4.6954210090568225, 'Adjusted R-Squared': 8.59389467874243, 'RMSE': 7695739.851972013, 'Time taken': 0.010997533798217773}
{'Model': 'XGBRegressor', 'R-Squared': -4.76392844302503, 'Adjusted R-Squared': 8.685237924033373, 'RMSE': 7741885.646007954, 'Time taken': 0.059577226638793945}
{'Model': 'LGBMRegressor', 'R-Squared': -4.373799372199783, 'Adjusted R-Squared': 8.16506582959971, 'RMSE': 7475292.417218507, 'Time taken': 0.029598712921142578}

In [ ]:
models

,Adjusted R-Squared,R-Squared,RMSE,Time Taken
Model,,,,
Lars,71.22,-51.66,23401328.08,0.01
BaggingRegressor,12.86,-7.89,9616634.28,0.02
RandomForestRegressor,10.67,-6.25,8683349.10,0.08
KNeighborsRegressor,9.36,-5.27,8076510.14,0.01
Lasso,9.35,-5.26,8069505.22,0.01
Ridge,9.09,-5.07,7941974.75,0.01
OrthogonalMatchingPursuit,8.85,-4.89,7822909.30,0.01
OrthogonalMatchingPursuitCV,8.85,-4.89,7822909.30,0.01
AdaBoostRegressor,8.76,-4.82,7780162.87,0.05
ElasticNet,8.75,-4.81,7774571.23,0.01
ExtraTreesRegressor,8.69,-4.76,7741887.91,0.06
ExtraTreeRegressor,8.69,-4.76,7741887.91,0.01
DecisionTreeRegressor,8.69,-4.76,7741887.91,0.01
GaussianProcessRegressor,8.69,-4.76,7741887.91,0.02
XGBRegressor,8.69,-4.76,7741885.65,0.06
GradientBoostingRegressor,8.69,-4.76,7741814.59,0.02
RidgeCV,8.64,-4.73,7717918.72,0.01
TweedieRegressor,8.59,-4.70,7695739.85,0.01
GammaRegressor,8.55,-4.66,7674810.69,0.01
LGBMRegressor,8.17,-4.37,7475292.42,0.03
DummyRegressor,8.17,-4.37,7475292.42,0.01
HistGradientBoostingRegressor,8.17,-4.37,7475292.42,0.04
BayesianRidge,8.17,-4.37,7475292.42,0.02
ElasticNetCV,8.16,-4.37,7474347.64,0.04
LassoLarsIC,8.07,-4.30,7426931.27,0.01
LassoCV,8.02,-4.27,7400706.52,0.06
LassoLarsCV,8.02,-4.27,7400648.45,0.02
LarsCV,8.02,-4.27,7400648.45,0.02
RANSACRegressor,8.00,-4.25,7387485.82,0.02
PoissonRegressor,7.74,-4.06,7251721.56,0.02
LassoLars,7.43,-3.82,7081321.70,0.01
TransformedTargetRegressor,7.43,-3.82,7079892.83,0.01
LinearRegression,7.43,-3.82,7079892.83,0.01
SVR,7.20,-3.65,6954786.95,0.01
QuantileRegressor,7.08,-3.56,6887126.89,0.02
HuberRegressor,6.88,-3.41,6771487.40,0.02
NuSVR,6.83,-3.37,6741061.95,0.01
SGDRegressor,6.15,-2.86,6336379.59,0.01
MLPRegressor,6.07,-2.80,6287792.33,0.05
LinearSVR,6.07,-2.80,6287499.55,0.01
PassiveAggressiveRegressor,5.56,-2.42,5962119.30,0.01
KernelRidge,3.59,-0.94,4491325.09,0.01

In [ ]:
predictions

,AdaBoostRegressor,BaggingRegressor,BayesianRidge,DecisionTreeRegressor,DummyRegressor,ElasticNet,ElasticNetCV,ExtraTreeRegressor,ExtraTreesRegressor,GammaRegressor,GaussianProcessRegressor,GradientBoostingRegressor,HistGradientBoostingRegressor,HuberRegressor,KNeighborsRegressor,KernelRidge,Lars,LarsCV,Lasso,LassoCV,LassoLars,LassoLarsCV,LassoLarsIC,LinearRegression,LinearSVR,MLPRegressor,NuSVR,OrthogonalMatchingPursuit,OrthogonalMatchingPursuitCV,PassiveAggressiveRegressor,PoissonRegressor,QuantileRegressor,RANSACRegressor,RandomForestRegressor,Ridge,RidgeCV,SGDRegressor,SVR,TransformedTargetRegressor,TweedieRegressor,XGBRegressor,LGBMRegressor
0,8891000.00,13609874.00,12141967.58,8891000.00,12141967.58,12052789.24,12141981.26,8891000.00,8891000.00,11996810.40,8891000.00,8891210.18,12141967.58,11405688.04,13214998.40,5796339.66,41724482.88,11806333.82,10946999.92,11822758.69,8567161.41,11806333.82,11551322.81,8568712.67,276.00,24.87,11317717.28,12600667.91,12600667.91,276000.00,8926388.31,11483527.73,8200330.88,11592124.78,11413585.09,12172541.51,9916146.24,11559995.66,8568712.67,12202043.22,8890999.00,12141967.58
1,13038000.00,16993600.00,12141967.58,13038000.00,12141967.58,15079333.59,12147316.81,13038000.00,13038000.00,14875108.06,13038000.00,13037876.66,12141967.58,11752121.27,14085469.20,6878669.23,-505499.67,13729915.01,15450634.26,13689588.24,12732155.95,13729915.01,14353992.50,12726022.59,210.00,36.33,11317717.79,15466108.98,15466108.98,210000.00,12736437.74,11483527.73,13001767.31,15656687.30,15585954.00,14818375.76,12858384.42,11559996.34,12726022.59,14710887.64,13037999.00,12141967.58
2,21026000.00,19390000.00,12141967.58,21026000.00,12141967.58,14401461.61,12146843.28,21026000.00,21026000.00,13968238.73,21026000.00,21025741.36,12141967.58,11705013.91,13137993.20,13590072.95,1818406.31,13319671.93,16360639.58,13288236.93,19577173.73,13319671.93,13806304.73,19579306.37,474.00,47.95,11317717.73,14382952.56,14382952.56,474000.00,20152043.12,11483527.73,20846129.44,18954371.24,15422274.17,14116725.41,14681922.06,11559996.60,19579306.37,14016715.80,21025994.00,12141967.58
3,9304548.00,8839330.60,12141967.58,9059000.00,12141967.58,8459387.37,12131071.26,9059000.00,9059000.00,8891264.07,9059000.00,9058829.85,12141967.58,10751190.76,10676599.80,-1937242.68,-19909204.79,9687169.53,8155404.41,9754163.40,8585927.46,9687169.53,8649917.38,8582089.95,12.00,15.20,11317717.21,7687076.54,7687076.54,12000.00,8636301.58,11483527.73,9010497.21,9395695.19,8049567.93,8709383.82,4823184.16,11559994.17,8582089.95,8816965.87,9058999.00,12141967.58
4,12877000.00,14439364.60,12141967.58,12877000.00,12141967.58,13148581.65,12144663.84,12877000.00,12877000.00,12812645.28,12877000.00,12877061.75,12141967.58,11590691.89,12999948.40,13499985.15,29426598.87,12800610.38,14694399.92,12776685.84,12280648.90,12800610.38,13171608.95,12279621.05,540.00,46.54,11317717.59,12462811.64,12462811.64,540000.00,11965786.95,11483527.73,11729821.36,13798397.52,13925993.83,12984119.95,13458799.44,11559996.39,12279621.05,12932628.31,12876999.00,12141967.58

now we pick linear regression for optimize

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures,OneHotEncoder,StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

preprocessor = ColumnTransformer(
    transformers=[
        ('ohe', OneHotEncoder(), ['Month Text']),
        ('std_scale', StandardScaler(),X_train.select_dtypes('number').columns)
    ])

X_train_pro = preprocessor.fit_transform(X_train)
X_test_pro = preprocessor.transform(X_test)

In [ ]:
param = {
        'poly__degree' : [1,2,3]
        }

pipeline = Pipeline(steps=[        
            ('poly', PolynomialFeatures()),
            ('lr', LinearRegression())
])

gridsearch = GridSearchCV(pipeline, param, cv=3, verbose=1)
gridsearch.fit(X_train_pro, y_train_pro)

NameError: name 'y_train_pro' is not defined

In [ ]:
gridsearch.best_params_

{'poly__degree': 1}

In [ ]:
lr = LinearRegression()
lr.fit(X_train_pro,y_train_pro)

lr.coef_

array([ 1355552.08477394,  4050530.93836443, -2486377.45551968,
       -2269291.27530807, -2406830.88503408, -1636764.18334072,
        1989358.15181328,  5519930.48248571, -1206924.38941947,
       -3632690.5375166 ,  2549125.72332674, -1825618.65462548,
         308683.50651539,  -336192.52443809, -1020272.42058472,
         266737.14176206, -1941317.90540577,  -474208.78078015])

In [ ]:
lr.predict(X_test_pro)

array([ 8891000.        , 13038000.        , 21026000.00000001,
        9059000.        , 12877000.        ])

In [ ]:
df_fullyear_sale_goal_test

,Month Text,Work Completion Score,Final Score,Work Score (%),Work Completion Score (%),Attitude Score (%),Final Score (%),Month_x,Month_y,Loan Amount
0,January,6.66,5.57,27.40,66.60,80.60,55.80,1.00,January,1950000
1,February,4.63,4.12,35.75,46.50,65.50,41.25,2.00,February,4191960
2,March,5.76,4.67,30.25,57.50,65.50,46.75,3.00,March,11046500
3,April,13.33,8.06,50.00,133.50,85.25,80.75,4.00,April,3133000
4,May,6.47,5.62,53.50,64.75,61.75,56.50,5.00,May,6668430

Create another non-parametric model

In [ ]:
from sklearn.tree import DecisionTreeRegressor

tree = DecisionTreeRegressor()
tree.fit(X_train_pro,y_train_pro)
tree.predict(X_test_pro)

array([ 8891000., 13038000., 21026000.,  9059000., 12877000.])

Same prediction score -> this is because too few train samples so the model fails to learn anything and only fit to the few instances

In [ ]:
loan_df = pd.read_excel('Encompass Data Feb 16 2023.xlsx')
loan_df = loan_df.loc[loan_df['Active Loan']=='No']
loan_df.shape

(214, 44)

In [ ]:
loan_df['Month'] = loan_df['Date Completed'].astype(str)
loan_df['Month'] = loan_df['Month'].apply(lambda x: x[5:7])

In [ ]:
loan_df.head()

,Application Date,Loan Created Date,Borrower Name,Loan Amount,Loan Purpose,Loan Processor,Current Loan Team Member,Subject Property Address,Subject Property City,Subject Property State,Lender Name,Borr DOB,Borr Sex Male/Female,Borr Age,Borr Marital Status,Borr Employer,Borr Present Addr,Borr Present City,Borr Actual Fico Score,Borr Present Zip,Borrower Mailing Addr,Borrower Mailing City,Borrower Mailing Zip,Property Value,Subject Property Purchase Price,Subject Property Type,Subject Property Zip,Loan Program,Loan Type,Interest Rate,Down Payment Amount,Down Pmt %,Income Total Mo Income,Income Total Mo Income (Borr/Co-Borr),Total Monthly Payment,CLTV,Top,Bottom Ratio,Total Loan Amount,Loan Term,Occupancy (P/S/I),Occupancy Type,Active Loan,Date Completed,Month
0,03/14/2022,3/14/2022 5:17:00 PM,"WU, LAWRENCE",1625000,Cash-Out Refi,Tram Nguyen,Tram Nguyen,18394 MONTPERE WAY,Saratoga,CA,Amwest,1964-01-05 00:00:00,,58,Married,NUSMILE DENTAL,730 S EL MONTE AVE,Los Altos,779,94022,730 S EL MONTE AVE,Los Altos,94022,2500000,0,Detached,95070,2 year,Conventional,6.000,,0.00,174000.00,174000.00,9742.70,65.00,17.16,40.88,1625000,30,Investment,Non-Owner Occupied,No,2022-05-12 00:00:00,05
1,01/06/2022,1/6/2022 7:49:00 PM,"WU, LAWRENCE",5000000,Cash-Out Refi,Tram Nguyen,Tram Nguyen,780 S. EL MONTE AVE,LOS ALTOS,CA,,1964-01-05 00:00:00,,58,Married,NUSMILE DENTAL,730 S EL MONTE AVE,Los Altos,,94022,730 S EL MONTE AVE,Los Altos,94022,8550000,0,Detached,94022,Conventional F,Conventional,4.875,,0.00,164000.00,164000.00,26460.41,97.56,18.20,48.48,5000000,30,Investment,Non-Owner Occupied,No,2022-03-09 00:00:00,03
4,05/25/2022,5/25/2022 5:05:00 PM,"Do, Nghiem Duy",1720000,Purchase,,MinhChau Nguyen,583 Gull Dr,Bodega Bay,CA,,1979-09-17 00:00:00,,42,Married,Lockheed Martin Corpor,4370 Quimby Road,San Jose,755,95148,4370 Quimby Road,San Jose,95148,2150000,2150000,Attached,94923,,Conventional,,430000,20.00,76694.00,76694.00,10590.34,80.00,11.01,36.69,1720000,30,Secondary,Owner Occupied,No,2022-06-24 00:00:00,06
13,02/23/2022,2/23/2022 9:56:00 AM,"NGUYEN, DONG HOAI",1500000,Other,Christine Le,Christine Le,TBD,,,,1980-06-29 00:00:00,Male,41,Unmarried,BASCOM VALLEY DENTAL I,2299 S KING ROAD,San Jose,790,95122,2299 S KING ROAD,San Jose,95122,1900000,1900000,Detached,,Conventional F,Conventional,,400000,21.05,37000.00,37000.00,8516.84,78.95,6.40,44.45,1500000,30,Investment,Non-Owner Occupied,No,2022-02-23 00:00:00,02
15,02/23/2022,2/23/2022 1:37:00 PM,"WONG, KIT CHUN",1415000,Purchase,Christine Le,Christine Le,351-353-253A-253B 29th Ave,San Francisco,CA,,1963-05-18 00:00:00,Female,58,Married,TEA MOTION INC,248 HARVARD RD,SAN MATEO,,94402,,,,NaN,2315000,Detached,94121,Conventional F,Conventional,NaN,900000,38.88,35510.00,35510.00,8034.21,61.12,30.33,62.74,1415000,30,Investment,Non-Owner Occupied,No,2022-02-23 00:00:00,02

In [ ]:
#Fill the empty Month by Loan Created Date value
loan_df['Month'] = loan_df['Month'].replace('',np.nan).fillna(loan_df['Loan Created Date'].apply(lambda x: x.split('/')[0]))

In [ ]:
loan_df['Total Loan Amount'].isna().sum()

0

In [ ]:
cols_to_show = ['Month','Total Loan Amount','Loan Processor']
loan_df = loan_df[cols_to_show]
loan_df = loan_df.loc[loan_df['Total Loan Amount'] != 0]

In [ ]:
month_map = {
    '1': 1, '01': 1,
    '2': 2, '02': 2,
    '3': 3, '03': 3,
    '4': 4, '04': 4,
    '5': 5, '05': 5,
    '6': 6, '06': 6,
    '7': 7, '07': 7,
    '8': 8, '08': 8,
    '9': 9, '09': 9,
    '10': 10,
    '11': 11,
    '12': 12
}
loan_df['Month'] = loan_df['Month'].map(month_map)

In [ ]:
loan_df['Month'].value_counts()

3     45
2     34
4     25
8     21
5     20
1     20
6     18
9      7
12     5
10     4
7      4
11     2
Name: Month, dtype: int64

In [ ]:
loan_df = loan_df.sort_values('Month').reset_index(drop=True)
loan_df.head()
loan_df.to_csv('loan_status_full')

In [ ]:
loan_df_average = loan_df.groupby('Month').mean()
loan_df_average

       Total Loan Amount
Month
1              818274.55
2              695726.32
3              664758.67
4              488520.00
5              547175.00
6              556024.61
7              391750.00
8              551538.86
9              805800.00
10             697500.00
11             670948.50
12             784700.00

In [22]:
a = df_fullyear['Name'].unique()[1]
a

'DAT'

In [21]:
list_name = df_fullyear['Name'].unique()
list_name = list_name.tolist()
list_name.remove(a)
list_name

['LONG',
 'HUY',
 'VU',
 'THAI',
 'JAMES',
 'STEPHEN',
 'VY',
 'TRI',
 'THANH',
 'GIANG',
 'JOSE',
 'CHRIS',
 'ADA',
 'MINH']

In [ ]:
list = ['Minh','Dat','Hai']
list.remove('Minh')
list

['Dat', 'Hai']